[project]
authors = ["Glatzel <893016099@qq.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "torch-minimal"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "*"
pip = "*"
