line-length = 120
exclude = [".pixi"]

[format]
docstring-code-format = true
docstring-code-line-length = 80

[lint]
select = [
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "D2",   # flake8-docstrings
    "D3",   # flake8-docstrings
    "D4",   # flake8-docstrings
    "E",    # pycodestyle
    "EM",   # flake8-errmsg
    "F",    # Pyflakes
    "FURB", # refurb
    "I",    # isort
    "ICN",  # flake8-import-conventions
    "INT",  # flake8-gettext
    "NPY",  # NumPy-specific rules
    "PERF", # Perflint
    "PIE",  # flake8-pie
    "PT",   # flake8-pytest-style
    "PTH",  # flake8-use-pathlib
    "RUF",  # Ruff-specific rules
    "SIM",  # flake8-simplify
    "TCH",  # flake8-type-checking
    "TD",   # flake8-todos
    "TID",  # flake8-tidy-imports
    "TID",  # flake8-tidy-imports
    "TRY",  # tryceratops
    "UP",   # pyupgrade
    "W",    # pycodestyle
]

[lint.pydocstyle]
convention = "numpy"
