name: CI

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: main
    paths-ignore:
      - "*.md"
      - ".pre-commit-config.yaml"
  pull_request:
    paths-ignore:
      - "*.md"
      - ".pre-commit-config.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  version-check:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ github.token }}
    outputs:
      version: ${{ steps.get-version.outputs.version}}
      need_build: ${{steps.check-new-version.outputs.need_build}}
    steps:
      - name: get-version
        id: get-version
        run: |
          $version=gh release view -R pytorch/pytorch --json tagName -q .tagName
          Write-Output "pytorch: $version"
          echo "version=$version" >> "$env:GITHUB_OUTPUT"

      - name: check-new-version
        id: check-new-version
        run: |
          $current_versions=gh release list -R Glatzel/torch-minimal --json tagName

          write-output $current_versions

          if("$current_versions".Contains("${{ steps.get-version.outputs.version }}")){
            echo "need_build=false" >> "$env:GITHUB_OUTPUT"
            write-output "No new version found, skip build."
          }
          else{
            echo "need_build=true" >> "$env:GITHUB_OUTPUT"
            write-output "New version found, ${{steps.get-version.outputs.version}}"
          }

  build-release:
    # run this job when new version is found or push or pull_request
    # only create release on schedule or workflow_dispatch
    needs: version-check
    if: ${{needs.version-check.outputs.need_build =='true'|| github.event_name!='schedule'}}
    runs-on: windows-latest
    strategy:
        matrix:
            python_version: ["3.9","3.10","3.11","3.12","3.13"]
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          run-install: false

      - name: download whl
        run: |
          pixi run pip download torch==$torch_version `
              --platform win_amd64 `
              --python-version ${{matrix.python_version}} `
              --only-binary=:all: `
              -d ./download `
              --no-deps

      - name: expand whl
        run: Expand-Archive -Path ./download/*.whl -DestinationPath ./temp

      - name: remove dnnl
        run: Remove-Item ./temp/torch/lib/dnnl.lib

      - name: pack whl
        run: |
          $whl = Get-ChildItem -Path ./download | Select-Object -First 1
          $whl=$whl.Name
          New-Item ./dist -ItemType Directory
          Compress-Archive -Path ./temp/* -DestinationPath "./dist/$whl" -PassThru

      - name: Create Release
        if: ${{ github.event_name=='workflow_dispatch'||github.event_name=='schedule' }}
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.whl
          tag_name: ${{needs.version-check.outputs.version}}
